name: relogio_cursor
description: Gerenciador de Tarefas.

publish_to: 'none' 


version: 1.0.0+3

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  intl: ^0.18.0
  provider: ^6.1.1
  wear: ^1.1.0
  flutter_animate: ^4.5.0
  uuid: ^3.0.7
  meta: ^1.9.1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/dicop.png

